# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

include:
- r: release
- r: oldrel
- r: devel

r_packages:
  - covr

r_github_packages:
  - codecov/example-r

after_success:
  - Rscript -e 'library(covr);codecov()'